### ISSUE TITLE
Issue with getPokeIds()

### ISSUE THREAD

**Issue by Beltface** [719Ben/Facebook-Auto-Poker#1]
>>> myPoker.getPokeIds()
/Library/Python/2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "FBpoker.py", line 255, in getPokeIds
    pokeCount = countFind[item].split(" ")[0]
IndexError: list index out of range

Currently have 3 pokes in queue

Cleared queue and it returned a proper null set

**Comment by 719Ben** [comment]
I'm not sure why you are getting the insecure platform warning. I will have to look into that more.

Do you remember how many times you had poked someone? I think this error shows up when someone pokes you for the first time as Facebook doesn't like a number, which the code looks for. I will write a patch later tonight.

**Comment by Beltface** [comment]
I think out of the three, one of them was brand new.

**Comment by 719Ben** [comment]
Should be fixed with e3dacc28a5b2f9c830f5ebbc5413bd7c56ee2e82. Thanks for submitting an issue.

**Comment by Beltface** [comment]
np dude, thanks!
