### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by bn326160** [719Ben/Facebook-Auto-Poker#2]
# With 2-way auth
> You have two factor authorization enabled.
> Please enter your two factor authorization code:969524
> Unable to login

# Without 2-way auth
> You have two factor authorization enabled.
> Traceback (most recent call last):
>   File "examples.py", line 6, in <module>
>     myPoker = FBpoker.autoPoker("xxx", "xxx")
>   File "/home/pi/Facebook-Auto-Poker/FBpoker.py", line 130, in __init__
>     "lsd": auth_lsd,
> UnboundLocalError: local variable 'auth_lsd' referenced before assignment

**Comment by 719Ben** [comment]
Sorry to get to this so late. Could you please give me some more info on the facebook version you are running? I am having trouble recreating this. @bn326160

**Comment by bn326160** [comment]
There are Facebook versions? I'm from Belgium, but Facebook is set in English (US)

**Comment by 719Ben** [comment]
Sometimes Facebook locks you account when you try to log in too many times. Try to make sure you are not locked.
